### ISSUE TITLE
2/18/20: Auto update dependencies

### ISSUE THREAD

**Issue by zkoppert** [zkoppert/Carl-the-llama#40]
**Please note by far the quickest way to get a new feature is to file a Pull Request.**

## What are you trying to accomplish?

Easier to keep dependencies up to date

## Is there a way to do this currently with the app?

manually

## What assistance would you need if you were assigned to work on this?

none

## Other relevant information

use this
```
on:
  schedule:
  - cron: 0 0 * * 3
name: Update
jobs:
  package-update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: set remote url
      run: git remote set-url --push origin https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
    - name: package-update
      uses: taichi/actions-package-update@master
      env:
        AUTHOR_EMAIL: john@example.com
        AUTHOR_NAME: john
        EXECUTE: "true"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        LOG_LEVEL: debug
      with:
        args: -u --packageFile package.json --loglevel verbose
```
